main.py: Running...
-- Resolving <Call main.txt:5:1-5:10> --
success

-- Resolving <Call main.txt:6:1-6:14> --
success

-- Resolving <Call main.txt:7:1-7:12> --
7:5-7:6:expected <StrType main.txt:2:1-9:13>, got <NumType main.txt:2:1-9:13>
  with foo => def foo(string, string)

7:8-7:11:expected <NumType main.txt:2:1-9:13>, got <StrType main.txt:2:1-9:13>
  with foo => def foo(number, number)


-- Resolving <Call main.txt:8:1-8:12> --
8:10-8:11:expected <StrType main.txt:2:1-9:13>, got <NumType main.txt:2:1-9:13>
  with foo => def foo(string, string)

8:5-8:8:expected <NumType main.txt:2:1-9:13>, got <StrType main.txt:2:1-9:13>
  with foo => def foo(number, number)


-- Resolving <TypeAssert main.txt:9:1-9:13> --
9:1-9:4:expected <NumType main.txt:2:1-9:13>, got <StrType main.txt:2:1-9:13>


-- test_escaping
2:5-2:8:testing escaping {} $Self=<Identifier main.txt:2:5-2:8> $n=<ProcDecl main.txt:2:1-2:24>

main.py: Done.
Done
