test.py:XXX: error: FooNode has no 'does_not_exist' attribute
Done
