test.py:10: error: FooNode has no 'does_not_exist' attribute
Done
